package com.project.entities;
// Generated 06/12/2019 04:06:11 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Miembrosjovenes generated by hbm2java
 */
@Entity
@Table(name = "miembrosjovenes")
public class Miembrosjovenes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Id
	private int idjovmiembros;
	@Column
	private String nombresyApellidos;
	@Column
	private String dni;
	@Column
	private Date fecNacimiento;
	@Column
	private Date fecConversion;
	@Column
	private Date fecBautismo;
	@Column
	private Date fecPacto;
	@Column
	private Integer edad;
	@Column
	private Character condicionEspiritual;
	@Column
	private Character mayor18varon;
	@Column
	private Character mayor18dama;
	@Column
	private String ubicacion;

	public Miembrosjovenes() {
	}

	public Miembrosjovenes(int idjovmiembros) {
		this.idjovmiembros = idjovmiembros;
	}

	public Miembrosjovenes(int idjovmiembros, String nombresyApellidos, String dni, Date fecNacimiento,
			Date fecConversion, Date fecBautismo, Date fecPacto, Integer edad, Character condicionEspiritual,
			Character mayor18varon, Character mayor18dama, String ubicacion) {
		this.idjovmiembros = idjovmiembros;
		this.nombresyApellidos = nombresyApellidos;
		this.dni = dni;
		this.fecNacimiento = fecNacimiento;
		this.fecConversion = fecConversion;
		this.fecBautismo = fecBautismo;
		this.fecPacto = fecPacto;
		this.edad = edad;
		this.condicionEspiritual = condicionEspiritual;
		this.mayor18varon = mayor18varon;
		this.mayor18dama = mayor18dama;
		this.ubicacion = ubicacion;
	}

	public int getIdjovmiembros() {
		return this.idjovmiembros;
	}

	public void setIdjovmiembros(int idjovmiembros) {
		this.idjovmiembros = idjovmiembros;
	}

	public String getNombresyApellidos() {
		return this.nombresyApellidos;
	}

	public void setNombresyApellidos(String nombresyApellidos) {
		this.nombresyApellidos = nombresyApellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	public Date getFecConversion() {
		return this.fecConversion;
	}

	public void setFecConversion(Date fecConversion) {
		this.fecConversion = fecConversion;
	}

	public Date getFecBautismo() {
		return this.fecBautismo;
	}

	public void setFecBautismo(Date fecBautismo) {
		this.fecBautismo = fecBautismo;
	}

	public Date getFecPacto() {
		return this.fecPacto;
	}

	public void setFecPacto(Date fecPacto) {
		this.fecPacto = fecPacto;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Character getCondicionEspiritual() {
		return this.condicionEspiritual;
	}

	public void setCondicionEspiritual(Character condicionEspiritual) {
		this.condicionEspiritual = condicionEspiritual;
	}

	public Character getMayor18varon() {
		return this.mayor18varon;
	}

	public void setMayor18varon(Character mayor18varon) {
		this.mayor18varon = mayor18varon;
	}

	public Character getMayor18dama() {
		return this.mayor18dama;
	}

	public void setMayor18dama(Character mayor18dama) {
		this.mayor18dama = mayor18dama;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

}
